---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: r2dbc-h2
- name: r2dbc-spi-artifactory

outputs:
- name: r2dbc-h2-artifactory

caches:
- path: maven

run:
  path: r2dbc-h2/ci/build.sh
